name = "Probably"
uuid = "5f4fb16a-da98-11e8-1fda-cfbf3a1ac577"
authors = ["jakobnissen <jakobnybonissen@gmail.com>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
Documenter = "~0.20"
